package q4;

import java.util.ArrayList;
import kotlin.jvm.internal.t;
import m4.g;
import org.json.JSONException;
import org.json.JSONObject;

public final class c implements i {
    public static g b(String str) {
        String str2 = str;
        t.e(str2, "jsonString");
        try {
            JSONObject jSONObject = new JSONObject(str2).getJSONObject("coreUiLabels");
            String optString = jSONObject.optString("initScreenTitle");
            t.d(optString, "coreUiLabels.optString(\"initScreenTitle\")");
            String optString2 = jSONObject.optString("agreeButton");
            t.d(optString2, "coreUiLabels.optString(\"agreeButton\")");
            String optString3 = jSONObject.optString("agreeAllButton");
            t.d(optString3, "coreUiLabels.optString(\"agreeAllButton\")");
            String optString4 = jSONObject.optString("initScreenRejectButton");
            t.d(optString4, "coreUiLabels.optString(\"initScreenRejectButton\")");
            String optString5 = jSONObject.optString("initScreenSettingsButton");
            t.d(optString5, "coreUiLabels.optString(\"initScreenSettingsButton\")");
            t.d(jSONObject, "coreUiLabels");
            ArrayList b5 = h.b(jSONObject, "summaryScreenBodyNoRejectService");
            ArrayList b6 = h.b(jSONObject, "summaryScreenBodyNoRejectGlobal");
            ArrayList b7 = h.b(jSONObject, "summaryScreenBodyNoRejectGroup");
            ArrayList b8 = h.b(jSONObject, "summaryScreenBodyRejectService");
            ArrayList b9 = h.b(jSONObject, "summaryScreenBodyRejectGlobal");
            ArrayList b10 = h.b(jSONObject, "summaryScreenBodyRejectGroup");
            String optString6 = jSONObject.optString("initScreenBodyGlobal");
            t.d(optString6, "coreUiLabels.optString(\"initScreenBodyGlobal\")");
            String optString7 = jSONObject.optString("initScreenBodyService");
            t.d(optString7, "coreUiLabels.optString(\"initScreenBodyService\")");
            String optString8 = jSONObject.optString("initScreenBodyGroup");
            t.d(optString8, "coreUiLabels.optString(\"initScreenBodyGroup\")");
            String optString9 = jSONObject.optString("specialPurposesAndFeatures");
            String str3 = optString8;
            t.d(optString9, "coreUiLabels.optString(\"…cialPurposesAndFeatures\")");
            String optString10 = jSONObject.optString("saveAndExitButton");
            String str4 = optString9;
            t.d(optString10, "coreUiLabels.optString(\"saveAndExitButton\")");
            String optString11 = jSONObject.optString("purposeScreenVendorLink");
            String str5 = optString10;
            t.d(optString11, "coreUiLabels.optString(\"purposeScreenVendorLink\")");
            String optString12 = jSONObject.optString("legitimateInterestLink");
            String str6 = optString11;
            t.d(optString12, "coreUiLabels.optString(\"legitimateInterestLink\")");
            String optString13 = jSONObject.optString("specialPurposesLabel");
            String str7 = optString12;
            t.d(optString13, "coreUiLabels.optString(\"specialPurposesLabel\")");
            String optString14 = jSONObject.optString("specialFeaturesLabel");
            String str8 = optString13;
            t.d(optString14, "coreUiLabels.optString(\"specialFeaturesLabel\")");
            String optString15 = jSONObject.optString("featuresLabel");
            String str9 = optString14;
            t.d(optString15, "coreUiLabels.optString(\"featuresLabel\")");
            String optString16 = jSONObject.optString("dataDeclarationLabel");
            String str10 = optString15;
            t.d(optString16, "coreUiLabels.optString(\"dataDeclarationLabel\")");
            String optString17 = jSONObject.optString("back");
            String str11 = optString16;
            t.d(optString17, "coreUiLabels.optString(\"back\")");
            String optString18 = jSONObject.optString("onLabel");
            String str12 = optString17;
            t.d(optString18, "coreUiLabels.optString(\"onLabel\")");
            String optString19 = jSONObject.optString("offLabel");
            String str13 = optString18;
            t.d(optString19, "coreUiLabels.optString(\"offLabel\")");
            String optString20 = jSONObject.optString("multiLabel");
            String str14 = optString19;
            t.d(optString20, "coreUiLabels.optString(\"multiLabel\")");
            String optString21 = jSONObject.optString("legalDescription");
            String str15 = optString20;
            t.d(optString21, "coreUiLabels.optString(\"legalDescription\")");
            String optString22 = jSONObject.optString("showPartners");
            String str16 = optString21;
            t.d(optString22, "coreUiLabels.optString(\"showPartners\")");
            String optString23 = jSONObject.optString("hidePartners");
            String str17 = optString22;
            t.d(optString23, "coreUiLabels.optString(\"hidePartners\")");
            String optString24 = jSONObject.optString("vendorScreenBody");
            String str18 = optString23;
            t.d(optString24, "coreUiLabels.optString(\"vendorScreenBody\")");
            String optString25 = jSONObject.optString("privacyPolicyLabel");
            String str19 = optString24;
            t.d(optString25, "coreUiLabels.optString(\"privacyPolicyLabel\")");
            String optString26 = jSONObject.optString("descriptionLabel");
            String str20 = optString25;
            t.d(optString26, "coreUiLabels.optString(\"descriptionLabel\")");
            String optString27 = jSONObject.optString("legitimateScreenBody");
            String str21 = optString26;
            t.d(optString27, "coreUiLabels.optString(\"legitimateScreenBody\")");
            String optString28 = jSONObject.optString("legitimateInterestPurposesLabel");
            String str22 = optString27;
            t.d(optString28, "coreUiLabels.optString(\n…sLabel\"\n                )");
            String optString29 = jSONObject.optString("legitimateInterestVendorLabel");
            String str23 = optString28;
            t.d(optString29, "coreUiLabels.optString(\n…rLabel\"\n                )");
            String optString30 = jSONObject.optString("legitimateScreenObject");
            String str24 = optString29;
            t.d(optString30, "coreUiLabels.optString(\"legitimateScreenObject\")");
            String optString31 = jSONObject.optString("legitimateScreenObjected");
            String str25 = optString30;
            t.d(optString31, "coreUiLabels.optString(\"legitimateScreenObjected\")");
            String optString32 = jSONObject.optString("legitimateScreenAccept");
            String str26 = optString31;
            t.d(optString32, "coreUiLabels.optString(\"legitimateScreenAccept\")");
            String optString33 = jSONObject.optString("objectAllButton");
            String str27 = optString32;
            t.d(optString33, "coreUiLabels.optString(\"objectAllButton\")");
            String optString34 = jSONObject.optString("persistentConsentLinkLabel");
            String str28 = optString33;
            t.d(optString34, "coreUiLabels.optString(\"…sistentConsentLinkLabel\")");
            String optString35 = jSONObject.optString("nonIabVendorsNotice");
            String str29 = optString34;
            t.d(optString35, "coreUiLabels.optString(\"nonIabVendorsNotice\")");
            String optString36 = jSONObject.optString("googlePartners");
            String str30 = optString35;
            t.d(optString36, "coreUiLabels.optString(\"googlePartners\")");
            String optString37 = jSONObject.optString("purposesLabel");
            String str31 = optString36;
            t.d(optString37, "coreUiLabels.optString(\"purposesLabel\")");
            String optString38 = jSONObject.optString("cookieMaxAgeLabel");
            String str32 = optString37;
            t.d(optString38, "coreUiLabels.optString(\"cookieMaxAgeLabel\")");
            String optString39 = jSONObject.optString("daysLabel");
            String str33 = optString38;
            t.d(optString39, "coreUiLabels.optString(\"daysLabel\")");
            String optString40 = jSONObject.optString("secondsLabel");
            String str34 = optString39;
            t.d(optString40, "coreUiLabels.optString(\"secondsLabel\")");
            String optString41 = jSONObject.optString("cookieAccessLabel");
            String str35 = optString40;
            t.d(optString41, "coreUiLabels.optString(\"cookieAccessLabel\")");
            String optString42 = jSONObject.optString("yesLabel");
            String str36 = optString41;
            t.d(optString42, "coreUiLabels.optString(\"yesLabel\")");
            String optString43 = jSONObject.optString("noLabel");
            String str37 = optString42;
            t.d(optString43, "coreUiLabels.optString(\"noLabel\")");
            String optString44 = jSONObject.optString("storageDisclosureLabel");
            t.d(optString44, "coreUiLabels.optString(\"storageDisclosureLabel\")");
            String optString45 = jSONObject.optString("dataRetentionDays");
            t.d(optString45, "coreUiLabels.optString(\"dataRetentionDays\")");
            return new g(optString, optString2, optString3, optString4, optString5, b5, b6, b7, b8, b9, b10, optString6, optString7, str3, str4, str5, str6, str7, str8, str9, str10, str11, str12, str13, str14, str15, str16, str17, str18, str19, str20, str21, str22, str23, str24, str25, str26, str27, str28, str29, str30, str31, str32, str33, str34, str35, str36, str37, optString43, optString44, optString45);
        } catch (JSONException unused) {
            return new g();
        }
    }

    public final /* bridge */ /* synthetic */ Object a(String str) {
        return b(str);
    }
}
